mapbox/carmen-cache

src/binding.cpp
test/setRelevance.test.js

Addresses two crashing cases:
- Very long queries (> 12 terms)
- Super irrelevant queries (relevance falls below 0)

Fixes for overflow errors

---

package.json
src/binding.cpp
test/setRelevance.test.js

Improves maximization in setRelevance in cases where an early Relev object would block later possible permutations which score higher.
In `master` currently this function iterates over a stack like this:
a b c d
Potentially dropping consideration of `b` (for example) if `a` is from the same index.
This branch adjusts setRelevance to consider several more combinations by iterating like this:
a b c d
b c d
c d
d
This leads to *not* a theoretically optimal maximum -- but actually hits many maximizing cases in practice. Example stack with index values above:
1 1 2 2
a b c d
Will currently hit all *maximizing* premutations in this case:
a c 
a d (when d leads to higher relev than c)
b c
b d (when d leads to higher relev than c)
Example where not all maximizing cases will be tried:
1 2 2 3 3
a …

[notready] Try more stacking permutations in setRelevance

---

package.json
src/binding.cpp
test/phrasematchPhraseRelev.test.js

0     1  2  3
query:  queen st st john
phrase:       st    john
Currently, the relev for this phrase is calculated to be < 1 because it short circuits at the first `st` match. When the loop gets to john@3 it's found to be non-contiguous with the previous match for st@1.
The fix in this branch ditches using queryidx/lastidx (which only represents the index of the *first* occurrence of a term in a query) and instead looks for overlap between termmasks:
0     1  2  3
query:  queen st st john
mask st:    0110
mask john:  1000
When looking at `john`, the previous matched term's mask for `st` is shifted to the left 1 and &'d to find overlaps:
mask st:    1100 <= shifted 1 bit to the left
mask john:  1000
This approach leaves open the possibility of corner cases like this:
query:  A B D B C …

Repeated neighbor term phraseRelev fix

---

package.json
src/binding.cpp
test/setRelevance.test.js

Fixes a bug where multiple relevs matching the same query reason from the same group could be counted multiple times. Adds tests for this case as well.

Setrelev fix

---

package.json
src/binding.cpp
test/setRelevance.test.js

Previously:
query: c a b
stack: a b c
Would score at best the `a b` portion of the stack.
Now:
query: c a b
stack: a b c
Full marks for `a b`, half marks for `c` since it goes "backwards" to the query flow to match.

Allow arbitrary order in setrelevance

---

proto/index.proto
src/binding.cpp
src/binding.hpp

My understanding is that keys are intended to be 32 bit unsigned int (based on reviewing https://github.com/mapbox/carmen#index-structure). However the code has been using 64 bit in a few places when this is unneeded. All tests pass with this change which indicates the `index.proto` change is harmless, but this should be further tested.

Use 32 bit keys

---

src/binding.cpp
test/coalesce.test.js

Sort covers at coalesce, preferring ones with higher relevance to those with lower.
Stopgap until implementing coalesced stacking of permutations. https://github.com/mapbox/carmen/issues/295

Sort covers

---

package.json
src/binding.cpp
test/coalesce.bench.test.js
test/coalesce.test.js

This PR coordinates with `carmen@closetomyheart` -- improving proximity mode by considering both score and distance together in a combined heuristic. It models the logic in carmen but at the earlier spatialmatch stage -- see upcoming carmen PR for detailed explanation.

scoredist (score + distance heuristic) for proximity

---

package.json
proto/index.proto
src/binding.cpp
src/binding.hpp
test/cache.test.js
test/coalesce.bench.test.js

Rolls back https://github.com/mapbox/carmen-cache/pull/29 and more to make 64-bit keys possible. Has reverberating effects in carmen so will coordinate there.

64-bit keys

---

package.json
src/binding.cpp
src/binding.hpp

This does what was proposed in #40 and switches the internal representation of the ldict to 32 bits. The external interface is unchanged, but only the 32 least significant bits of the 64-bit input hash are used.
Running the French address test, peak memory usage is down about 35%, from ~5.5 gigs to ~3.4 over the test run. The number of positives at this loop:
https://github.com/mapbox/carmen/blob/master/lib/phrasematch.js#L54
increased by 3, from 9049 to 9052, so, a tiny fraction of a percent, with no appreciable difference to either compute time or results over this test.
So... I think it works?
cc @mapbox/geocoding-gang

switch to only storing 32 bits of the 64-bit hashes in the ldict

---

package.json
src/binding.cpp
src/binding.hpp

I noticed https://github.com/mapbox/protozero/commit/4e7e32ac5350ea6d3dcf78ff5e74faeee513a6e1 and this pull upgrades to that new API.
/cc @joto @flippmoke for gut check that my usage is optimal.
@apendleton @yhahn - I'm not seeing meaningful benchmarks for `cache.pack`, so let me know if I might be missing them. At this point I assume this pull will increase `cache.pack` performance but this is not verified.

Upgrade to protozero 1.3.0

---

.travis.yml
src/binding.cpp

:hocho: :warning: 
Some explicit type conversions. Doesn't affect actual behavior of the code (these were going on anyway) but the compiler was spitting out warnings to make sure we know they're going on.
cc @mattficke

Clean up some type warnings

---

src/binding.cpp
test/cache.test.js
test/merge.test.js

In all cases where C++ exceptions are possible we should use `try/catch` to ensure the C++ exception is sent back to JS land as a JS Error. C++ functions in the threadpool should use try/catch and then set a property of the baton to pass the error back to the main thread.
Followups needed:
- coalesceSingle and coalesceMulti are also missing try/catch
/cc @sbma44 @yhahn @mapsam

Handle potential exception in mergeQueue

---

src/binding.cpp

Sorting by x and y in case of a tie doesn't produce better results, but it does produce more consistent output.
This avoid test failures like https://github.com/mapbox/carmen/issues/540

make cover sorting more deterministic

---

package.json
src/binding.cpp

Limits individual gridcache gets to
- 500000 entries and 
- 100000 on coalescesingle without proximity/bbox
This optimization prevents extremely large gridcache shards (usually those for early degens, e.g. `a`) from having an outsized impact on performance. Since gridcache shards are presorted when stored this optimization largely excludes low scoring, low relevance features from consideration during coalesce.
These covers were definitely thrown out anyway by the final step of coalesce making this change have functionally equivalent handling of the spatialmatch process.
**Note:** These thresholds were tested with real data but are definitely heuristics. Example theoretical problem case: an example of gridcache shard that would push the boundaries of the 100k limit, for example, would be …

Performance: gridcache limit on coalesce

---

.travis.yml
README.md
binding.gyp

This PR moves to depending on rocksdb via mason. This requires one-time manual install of mason and rocksdb locally. See `.travis.yml`/Readme diff for how to do it.

Rocksdb via mason

---

binding.gyp
common.gypi
package.json

This PR modernizes the build by applying learning and templates from https://github.com/mapbox/node-cpp-skel/ (:tada: thanks @GretaCB and @mapsam) and upgrading deps. Here is a rundown of the changes:
- Now using `product_dir` to copy the binary into the proper "versioned" spot for node-pre-gyp to be able to package portabily (reduces extra target)
- Removes the `deps/` and `<(SHARED_INTERMEDIATE_DIR)/` include directories - these were only needed back when we vendored libprotobuf (before moving to `protozero`)
- Upgrades `protozero` and starts dynamically finding its location using https://github.com/mapbox/protozero/pull/59. This avoids possible breakage downstream if another module depended on protozero and npm deduped it.
- Adds linker flags (`-Wl,-z,now` on linux, `-Wl,-bind_at_load` …

Modernize build

---

.npmignore
.travis.yml
binding.gyp
install_mason.sh

The [rocksdb via mason](https://github.com/mapbox/carmen-cache/pull/62) PR moved to mason for installing rocksdb, and installed mason and rocksdb in the `.travis.yml` file for running on CI, but otherwise required devs to manually install them. We often work on interacting carmen and carmen-cache changes with a carmen branch that points at a `/tarball` Github URL of a carmen-cache branch for which a `node-pre-gyp` prebuilt binary does not exist, and this was failing on the rocksdb branch because mason was not getting installed in that case. This PR moves the mason install into a node-gyp pre-build action so that it always gets run, regardless of whether it's on travis or as part of an npm install.
@springmeyer curious if you think this is a bad idea, and if so, if there are better ways to …

Move mason install from the travis yml to a pre-build gyp action

---

install_mason.sh

I've merged the rocksdb package for mason (https://github.com/mapbox/mason/pull/305). Let's merge this and afterward it will be safe to delete the `rocksdb-4.13` branch of mason.
/cc @apendleton

Use mason@master

---

src/binding.cpp
src/binding.hpp

The `coalesce` function needs to reference count the cache objects passed in. This PR starts doing this. Without reference counting the node.js garbage collector is allowed to collect the `Cache` objects before the threadpool is done working with them. This would result in invalid memory access in the `coalesce` code and therefore undefined behavior.
/cc @yhahn

Avoid possible invalid memory access in async coalesce

---

.travis.yml
src/binding.cpp

During a general code review I noticed a few small optimizations that could be made to `loadSync`:
- Avoiding trying to remove keys before inserting. This is only needed if we need to overwrite existing keys already in the cache but I see no sign in the tests that this is needed.
- Removing `std::make_pair` call from `list.emplace_front`. This will be called internally when arguments are forwarded and then constructed in-place.
- Passing the message string to `list.emplace_front` so that it is constructed once (in place rather than being allocated and then copied into place).
Running the `test/cache.bench.test.js` locally I get:
```
ok 3 loadSync x256 took 229ms
```
```
ok 3 loadSync x256 took 171ms
```

Optimize loadSync

---

.travis.yml

Low priority. But nonetheless various build fixes, each with a specific motivation:
- To ensure we can support C++14 we should explicitly upgrade to at least libstdc++-4.9-dev (unblocks #71)
- For best performance we should use the latest clang++ from mason as the target compiler (this upgrades to v3.9.1 - the latest stable release)
- For ease of maintenance we should target just node v0.10.x and the two LTS releases. This therefore moves to building against only v0.10.x, v4, and v6.

Build updates

---

.travis.yml
binding.gyp
common.gypi
src/binding.cpp

This optimizes the async merge implementation by significantly reducing memory allocations.
Previously a `std::string` was allocated and copied once for each of the two pbf buffers passed in. Now these buffers are passed in a zero-copy way by taking a pointer to their memory and marking them as `Persistent` to ensure they are safe to use in the threadpool (So the memory from JS is used directly in the C++ threadpool).
Also previously the final merged pbf (aka `pbf3` in the code) was allocated and copied twice: once in the threadpool (`baton->pbf3 = merged;`) and another time in `Nan::CopyBuffer`. Now instead we allocate once and pass in a zero-copy way directly into `Nan::NewBuffer`. We use C++14 features (`make_unique`) and a `unique_ptr` to accomplish this handoff. Also the buffer is …

Optimize merge code

---

.travis.yml
package.json
src/binding.cpp

From https://github.com/mapbox/carmen-cache/pull/70:
------
During a general code review I noticed a few small optimizations that could be made to `loadSync`:
- Avoiding trying to remove keys before inserting. This is only needed if we need to overwrite existing keys already in the cache but I see no sign in the tests that this is needed.
- Removing `std::make_pair` call from `list.emplace_front`. This will be called internally when arguments are forwarded and then constructed in-place.
- Passing the message string to `list.emplace_front` so that it is constructed once (in place rather than being allocated and then copied into place).
Running the `test/cache.bench.test.js` locally I get:
```
ok 3 loadSync x256 took 229ms
```
```
ok 3 loadSync x256 took 171ms
```

Optimize loadSync (redux)

---

package.json
src/binding.cpp

- @springmeyer's fixes for `std::move()` safety in coalesce()
- @yhahn's _One Small Trick To Optimize coalesce()_
Ready for release once IRL integration tests pass.

Move safely + coalesce optimization

---

package.json
src/binding.cpp
test/coalesce.test.js

- `carmen` currently supports a maximum of 20 query tokens (https://github.com/mapbox/carmen/blob/master/lib/constants.js#L7)
- `carmen-cache` represents the bit mask for subqueries using `unsigned short` which has 16 bits -- so it can at most represent a 16-token query
- What currently happens in some cases is not just bad/empty geocoding, but possibly horrendous resource usage because coalesceMulti relies on this mask check to prevent context cover lists from ballooning out of size (https://github.com/mapbox/carmen-cache/blob/e43612a30bcb37d93170b4b9cbc26facae78581e/src/binding.cpp#L1340)
- Adds a unit test that demonstrates how this failed mask check can lead to incorrect results and OOM. Testrun on travis here: https://travis-ci.org/mapbox/carmen-cache/jobs/196437543#L593
- Switches …

Expand 'mask' bitmask space from unsigned short to uint32_t (16=>32 bits)

---

common.gypi

Mason packages default to `D_GLIBCXX_USE_CXX11_ABI=0` for full capability across all linux versions pre and post the dubious duel-abi change (https://gcc.gnu.org/onlinedocs/libstdc%2B%2B/manual/using_dual_abi.html).
Recent ubuntu versions start defaulting to `D_GLIBCXX_USE_CXX11_ABI=1` so to ensure we can link correctly we need to set the default to `0` for the carmen cache compile. In the future mason may provide "duel" packages for both versions, maybe. Until then this is the way forward to ensure you can source compile on a recent ubuntu version.
@apendleton feel free to point this at the right rocksdb base.
/cc @yhahn

[rocksdb] Fix source compile with recent ubuntu

---

src/binding.cpp
test/coalesce.bench.test.js
test/coalesce.test.js

This fixes three potential crashes and adds more test coverage.
- #85 (SIGILL)
- #83 (SIGABRT)
- #81 (SIGSEGV)
It also refactors to remove the freestanding functions that took `v8::Local` objects as arguments. This is because these functions may need `HandleScopes` if not fully inlined. Therefore manually inlining them avoids a potential leak if the inlining does not happen.

More careful conversion of objects

---

.travis.yml
package.json
src/binding.cpp
src/binding.hpp
test/cache.test.js
test/coalesce.test.js
test/langfield.fuzz.test.js
test/matching.test.js

This is an implementation of the final multilingual grid proposal described [here](https://github.com/mapbox/carmen/issues/547). Grid keys are now annotated with a bitfield describing the languages to which the given combination of key and grids applies.
A bit of extra detail beyond the carmen PR (but read the carmen PR too)...
About the key format:
* this PR introduces an internal language field type, which is currently typedef'ed to an unsigned 128-bit int (using the nonstandard `__int128` clang intrinsic). The index format does not depend on these fields being 128-bit, however, as the language suffix is variably sized.
* keys are formatted as `key|langfield` (with an actual pipe character as the separator), and the langfield is a variable-width bit field that's copied into the least …

Language fields (for carmen@hyperpolyglot)

---

package.json

Moves to bundling as a best practice due to mapbox/node-pre-gyp#269

Bundle node-pre-gyp

---

README.md

This adds more details to the readme about how to install/build. This assumes #95 will merge.

Update install/build instructions in readme

---

src/binding.cpp
test/coalesce.test.js

- Adjusts `* 0.8` penalty to be `* 0.9`
Context: with the adjustments in https://github.com/mapbox/carmen/pull/645, previous data that primarily relied on default text to get "full" language match results will no longer. That makes a much larger swath of possible results get this penalty.
To make this change gentler on API consumer using `relev` to set thresholds, this makes the the penalty applied much gentler.
cc @mapbox/geocoding-gang

Make penalty for non-matching language matches gentler

---

src/binding.cpp

`clang-tidy` is a [static analyzer](https://github.com/mapbox/cpp/blob/master/glossary.md#static-analysis) capable of detecting a wide range of bugs and memory leaks.
@mapbox/core-tech is spearheading getting `clang-tidy` working for node c++ modules at https://github.com/mapbox/node-cpp-skel/issues/63.
In time we will provide docs for how to enable on `clang-tidy` on travis for `carmen-cache`.
Currently I ran `clang-tidy` locally to assess the codebase here and found two problems worth fixing quickly.
The following PR fixes a potential memory leak and incorrect usage of `std::move`. The incorrect `std::move` usage is minor. The memory leak could trigger if a new `RocksDBCache` is created in JS using an invalid or empty string, or if the database cannot be opened.

Fix two errors identified by clang-tidy

---

package.json
src/binding.cpp
src/binding.hpp
test/coalesce.bench.test.js
test/normalize.test.js

This PR adds a new class to carmen-cache that stores an int-to-int mapping in a rocksdb database. It has pretty much nothing to do with existing carmen-cache classes, but this was a convenient place to put this functionality given that we already have the infrastructure necessary to build against rocksdb.
It does a few things:
* store and retrieve int->int mappings
* given a range of ints, it can search through that range of keys and return all values outside the range.
Used as the accompanying storage for https://github.com/mapbox/dawg-cache/pull/17, this allows expressing the concept "search through all the keys that start with X and give me any values they map to that don't also start with X."

Normalizer cache

---

package.json
src/binding.cpp
test/normalize.test.js

This PR modifies the normalization cache to make it able to represent situations where a single phrase might normalize to multiple phrases within the index, by storing multiple integers in sequence as values in the normalization rocksdb database.
The new version can read and use databases created by the existing version without modification. Databases created by the new version can be used without error by the existing version but may not retrieve all normalization values from the database. The interface presented to Carmen has also changed, such that the get methods now return arrays instead of scalars, and the set methods accept arrays as well as scalars.

Multivariate calculus

---

binding.gyp
scripts/install_deps.sh
scripts/setup.sh

This is a fix on top of the `cache-split` branch. It should fix LTO on linux by:
- ensuring we're using a consistent compiler (clang++ via mason, setup via the scripts/setup.sh script)
- NOTE: I have dreams of a `mbxcxx` command that we use to do this in the future (rather than this clumsy `scripts/setup.sh` copied everywhere)
- ensure that the same compile is used to compile and link all binaries (important for being able to blend LTO binaries with other libraries).
Should fix https://github.com/mapbox/carmen-cache/issues/117#issuecomment-369051742

Fix LTO on linux

---

.npmignore

Our recent npm packages include our whole mason toolchain unnecessarily. The relevant directories are excluded from git but not from npm, so this PR updates the npmignore to match.
Ordinarily we would cut a carmen PR before merging this one, but I don't think it will be instructive as we won't actually know if this particular problem is solved until we cut a new release.
cc @mattficke

Better npmignore

---

package.json
scripts/install_deps.sh
scripts/setup.sh

This branch fixes #124 by switching to a portable build of RocksDB that should work on all architectures.
Changes:

Portable rocksdb

---

package.json
src/coalesce.cpp
src/cpp_util.hpp
src/rocksdbcache.cpp
src/rocksdbcache.hpp

This branch optimizes the `coalesce` function in these ways:
- It pre-filters `context` objects using `relev` score to mitigate the size of the `std::vector<Context>` object before sorting
- It reverts [several calls to `vector.reserve`](https://github.com/mapbox/carmen-cache/commit/1d55d3d63c09e40b2483d36a75a0f1787b3a3040) that were, based on profiling, incurring more overhead than efficiency gains because they were overallocating memory that was never written to. The rule of thumb should be to only call reserve when we know for sure that we'll use all the memory. Otherwise incurring re-allocation overhead will be less of a cost than over-allocating up front.
- It makes several classes movable, such that re-allocation of these objects in vectors (during growth or sorting) should be …

Optimize coalesce

---

API.md
bench/coalesce.bench.test.js
index.js
src/binding.cpp
src/cpp_util.hpp
src/memorycache.cpp
src/memorycache.hpp
src/rocksdbcache.cpp
src/rocksdbcache.hpp
test/coalesce.proximity.test.js
test/coalesce.test.js
test/matching.test.js

Get carmen-cache to respect tokenized words & not attempt to complete them for you. See https://github.com/mapbox/carmen/pull/795
This PR is a replacement for https://github.com/mapbox/carmen-cache/pull/137 after rebasing on the 0.22.0 refactor.
Current status; functional. Outstanding tasks;

Word boundary scan

---

scripts/install_deps.sh

These were needed to source compile rocksdb on travis. But we're no longer doing that after https://github.com/mapbox/carmen-cache/commit/14f138ebd31ccd03bc7b38acc2738321d93d2a55#diff-1d889b31bb06cb578abde8e2253d043aL6 (which is awesome) so these things can be removed to avoid any confusion.

Remove rocksdb related build hacks

---

package.json
src/binding.cpp
src/binding.hpp
src/coalesce.cpp
src/cpp_util.hpp
src/memorycache.cpp
src/memorycache.hpp
src/rocksdbcache.cpp
src/rocksdbcache.hpp
test/coalesce.test.js
test/matching.test.js

This PR introduces several changes in support of mapbox/carmen#813 , which adds autocomplete support for number-only address queries.
The changes:
UPDATE 6 Feb:
* I also played with a version that tried to do a smarter sort using repeated calls to `std::merge`, since the list we're sorting is comprised of a sequence of already-sorted lists. Turned out that once the prefiltering was done, the remaining list was small enough in practice that this approach didn't yield a significant performance improvement (sorting a few thousand things just doesn't take very long) but was much more complicated code-wise, so I ditched it.
* this new version of getMatching isn't exposed directly to Javascript, so it's only testable at present indirectly via calls to `coalesceSingle`. Eventually though, I …

Deduplicate grids, don't truncate memoized grid prefix lists, etc.

---

.npmignore

There are a few test config files that, while harmless, don't need to be in our npn packages. This PR adds them to .npmignore

Add some test files to .npmignore

---

src/cpp_util.cpp
test/coalesce.proximity.test.js
test/coalesce.test.js

In calculating scoredist, the distratio had a [hard-coded minimum value of 0.005](https://github.com/mapbox/carmen-cache/blob/master/src/cpp_util.cpp#L158-L161). The rationale behind this was that if as distratio approaches zero, the scordist value gets exponentially higher. The cap at 0.05 was hard-coded based on a proximity radius of 200, assuming that 0.05 was the minimum reasonable value (more explanation below).
This value of 0.005 is based on the minimum reasonable value for a proximity radius closer to 200. The problem is that when the proximity radius passed in to coalesce is higher, say 400, there is meaningful differentiation in the values that are less than 0.005.
Alternatively, any distance less than 1 isn't meaningful, since something on the same tile as the proximity point …

Distance floor
